### PR TITLE
fix(sdk): use correct controller during stream creation

### LINKED ISSUE #725: BUG: C1 SDK uses session DID Key as new stream controller instead of DID PKH

### PR DESCRIPTION
**Pull request by smrz2001**
cc @m0ar 

Closes #725

### CODE REVIEW

File: sdk/packages/model-instance-client/src/client.ts [hunk 1]
```diff
@@ -28,8 +28,8 @@ import type { DocumentState, UnknownContent } from './types.js'
 export type CreateSingletonParams = {
   /** The model's stream ID */
   model: StreamID
-  /** The controller of the stream (DID string or literal string) */
-  controller: DIDString | string
```
Comment (stbrody) [inline sdk/packages/model-instance-client/src/client.ts:32]: this is losing the ability for the user to set the controller DID string explicitly, but maybe that's fine?  Almost everyone is going to be using did-session anyway so maybe that doesn't really matter as a feature

Comment (smrz2001) [reply sdk/packages/model-instance-client/src/client.ts:32]: Yeah, I think that should be ok.

I _could_ have left the DID strings in but that would have meant leaving it to callers to check whether the DID had a parent PKH and then to pass that in, which felt risky.
